# Generated by Django 5.0.3 on 2024-05-04 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2024, 5, 4, 12, 43, 11, 286598)),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2024, 5, 4, 12, 43, 11, 286598)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=2),
        ),
    ]
