# Generated by Django 5.0.3 on 2024-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_expense_amount_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food & Drinks', 'Food & Drinks'), ('Shopping', 'Shopping'), ('House', 'House'), ('Transportation', 'Transportation'), ('Vehicle', 'Vehicle'), ('Life & Entertainment', 'Life & Entertainment'), ('Technology & Communication', 'Technology & Communication'), ('Taxes & Fees', 'Taxes & Fees'), ('Insurance', 'Insurance'), ('Investment', 'Investment')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Checks, cupons', 'Checks, cupons'), ('Investment', 'Investment'), ('Gifts', 'Gifts'), ('Lending', 'Lending'), ('Lottery', 'Lottery'), ('refunds', 'refunds'), ('Rental income', 'Rental income'), ('Sale', 'Sale'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
