# Generated by Django 5.0.3 on 2024-05-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transaction_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food & Drinks', 'Food & Drinks'), ('Shopping', 'Shopping'), ('House', 'House'), ('Transportation', 'Transportation'), ('Vehicle', 'Vehicle'), ('Life & Entertainment', 'Life & Entertainment'), ('Technology & Communication', 'Technology & Communication'), ('Taxes & Fees', 'Taxes & Fees'), ('Insurance', 'Insurance'), ('Investment', 'Investment'), ('Health & Fitness', 'Health & Fitness'), ('Education', 'Education'), ('Gifts & Donations', 'Gifts & Donations'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Checks, cupons', 'Checks, cupons'), ('Investment', 'Investment'), ('Gifts', 'Gifts'), ('Lending', 'Lending'), ('Lottery', 'Lottery'), ('Refunds', 'Refunds'), ('Rental income', 'Rental income'), ('Sale', 'Sale'), ('Wages', 'Wages'), ('Interest', 'Interest'), ('Other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('HOLIDAYS', 'HOLIDAYS'), ('NEW VEHICLE', 'NEW VEHICLE'), ('TRIP', 'TRIP'), ('SAVINGS', 'SAVINGS'), ('EMERGENCY FOUND', 'EMERGENCY FOUND'), ('NEW HOME', 'NEW HOME'), ('EDUCATION', 'EDUCATION'), ('HEALTH CARE', 'HEALTH CARE'), ('KIDS', 'KIDS'), ('TECNOLOGY', 'TECNOLOGY'), ('INVESTMENTS', 'INVESTMENTS'), ('Other', 'Other')], max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
