# Generated by Django 5.0.3 on 2024-05-05 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_expense_category_alter_income_category_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2024, 5, 5)),
        ),
    ]
