# Generated by Django 5.0.3 on 2024-05-05 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_goals_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=datetime.date(2024, 5, 5)),
        ),
    ]
