# Generated by Django 5.0.3 on 2024-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_goals_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
