# Generated by Django 5.0.3 on 2024-05-10 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_expense_date_alter_goals_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2024, 5, 10)),
        ),
        migrations.AlterField(
            model_name='goals',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=datetime.date(2024, 5, 10)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, verbose_name=datetime.date(2024, 5, 10)),
        ),
    ]
