# Generated by Django 5.0.3 on 2024-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_goals_start_date_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('I', 'Incomes'), ('E', 'Expenses'), ('G', 'Goals')], default='I', max_length=1),
        ),
    ]
