# Generated by Django 5.0.3 on 2024-05-16 12:03

from django.db import migrations

def create_preloaded_categories(apps, schema_editor):
    Category = apps.get_model('myapp', 'Category')
    Category.objects.create(name='Rent', icon='🏠', category_type='E', user=None)
    Category.objects.create(name='Food & Drinks', icon='🍔', category_type='E', user=None)
    Category.objects.create(name='Shopping', icon='🛍️', category_type='E', user=None)
    Category.objects.create(name='House', icon='🏠', category_type='E', user=None)
    Category.objects.create(name='Transportation', icon='🚗', category_type='E', user=None)
    Category.objects.create(name='Vehicle', icon='🚙', category_type='E', user=None)
    Category.objects.create(name='Life & Entertainment', icon='🎉', category_type='E', user=None)
    Category.objects.create(name='Technology & Communication', icon='📱', category_type='E', user=None)
    Category.objects.create(name='Taxes & Fees', icon='💰', category_type='E', user=None)
    Category.objects.create(name='Insurance', icon='🏥', category_type='E', user=None)
    Category.objects.create(name='Investment', icon='💼', category_type='E', user=None)
    Category.objects.create(name='Health & Fitness', icon='💪', category_type='E', user=None)
    Category.objects.create(name='Education', icon='🎓', category_type='E', user=None)
    Category.objects.create(name='Gifts & Donations', icon='🎁', category_type='E', user=None)
    Category.objects.create(name='Other', icon='🔧', category_type='E', user=None)
        # Create preloaded categories for incomes
    Category.objects.create(name='Salary', icon='💰', category_type='I', user=None)
    Category.objects.create(name='Checks, cupons', icon='💲', category_type='I', user=None)
    Category.objects.create(name='Investment', icon='💼', category_type='I', user=None)
    Category.objects.create(name='Gifts', icon='🎁', category_type='I', user=None)
    Category.objects.create(name='Lending', icon='💸', category_type='I', user=None)
    Category.objects.create(name='Lottery', icon='🎰', category_type='I', user=None)
    Category.objects.create(name='Rental Income', icon='🏠', category_type='I', user=None)
    Category.objects.create(name='Sale', icon='🤑', category_type='I', user=None)
    Category.objects.create(name='Wages', icon='💵', category_type='I', user=None)
    Category.objects.create(name='Interest', icon='📈', category_type='I', user=None)
    Category.objects.create(name='Other', icon='🔧', category_type='I', user=None)
        # Create prelodaded categories for goals
    Category.objects.create(name='Holidays', icon='🏖️', category_type='G', user=None)
    Category.objects.create(name='New Veichle', icon='🚗', category_type='G', user=None)
    Category.objects.create(name='Trip', icon='🛫', category_type='G', user=None)
    Category.objects.create(name='Savings', icon='💰', category_type='G', user=None)
    Category.objects.create(name='Emergency Found', icon='🚨', category_type='G', user=None)
    Category.objects.create(name='New Home', icon='🏡', category_type='G', user=None)
    Category.objects.create(name='Education', icon='🎓', category_type='G', user=None)
    Category.objects.create(name='Health Care', icon='❤️‍🩹', category_type='G', user=None)
    Category.objects.create(name='Kids', icon='👨‍👩‍👧‍👦', category_type='G', user=None)
    Category.objects.create(name='Tecnology', icon='🖥️', category_type='G', user=None)
    Category.objects.create(name='Investments', icon='💎', category_type='G', user=None)
    Category.objects.create(name='Others', icon='🔧', category_type='G', user=None)
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20240516_1359'),
    ]

    operations = [
    ]
