# Generated by Django 5.0.3 on 2024-05-25 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Incomes', 'Incomes'), ('Expenses', 'Expenses'), ('Goals', 'Goals')], max_length=10),
        ),
        migrations.AlterField(
            model_name='goals',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=datetime.date(2024, 5, 25)),
        ),
    ]
