# Generated by Django 5.0.3 on 2024-06-07 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_category_category_type_alter_goals_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=datetime.date(2024, 6, 7)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
