# Generated by Django 5.0.3 on 2024-06-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_goals_start_date_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
